// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkFel0fnxvMwSAseoKMfuJ4dM1i3LerTU',
    appId: '1:141679054231:web:758130589a22741d3888d2',
    messagingSenderId: '141679054231',
    projectId: 'p-m-s-34c04',
    authDomain: 'p-m-s-34c04.firebaseapp.com',
    storageBucket: 'p-m-s-34c04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaEU9mN50L52QGqhtZ1x81ZA3lDBafTuI',
    appId: '1:141679054231:android:ed488456ba013e903888d2',
    messagingSenderId: '141679054231',
    projectId: 'p-m-s-34c04',
    storageBucket: 'p-m-s-34c04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0obSmfUpSSEFQLJOTbBKO101reti3bI',
    appId: '1:141679054231:ios:67367af875771f023888d2',
    messagingSenderId: '141679054231',
    projectId: 'p-m-s-34c04',
    storageBucket: 'p-m-s-34c04.appspot.com',
    iosBundleId: 'com.example.pms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi0obSmfUpSSEFQLJOTbBKO101reti3bI',
    appId: '1:141679054231:ios:1a8168d18025367c3888d2',
    messagingSenderId: '141679054231',
    projectId: 'p-m-s-34c04',
    storageBucket: 'p-m-s-34c04.appspot.com',
    iosBundleId: 'com.example.pms.RunnerTests',
  );
}
